### ISSUE TITLE
Author information

### ISSUE THREAD

**Issue by ctb** [dib-lab/2020-paper-sourmash-gather#1]
@brooksph @taylorreiter @bluegenes will all be co-authors on this paper, fo' sure, perhaps along with others. This issue is to collect their information. Here is the YAML format we will need it in; please add in comments if you have the time :) .

```
  - github: luizirber
    name: Luiz Irber
    initials: LI
    orcid: 0000-0003-4371-9659
    twitter: luizirber
    email: lcirberjr@ucdavis.edu
    affiliations:
      - Graduate Group in Computer Science, UC Davis
      - Department of Population Health and Reproduction, UC Davis
    funders:
      - Grant XXXXXXXX
```

**Comment by taylorreiter** [comment]
```
  - github: taylorreiter
    name: Taylor Reiter
    initials: TER
    orcid: 0000-0002-7388-421X
    twitter: ReiterTaylor
    email: tereiter@ucdavis.edu
    affiliations:
      - Graduate Group in Food Science, UC Davis
      - Department of Population Health and Reproduction, UC Davis
    funders:
      - Grant XXXXXXXX
```

I'll edit this comment with my funding shortly...I've received a number of small scholarships through the Food Science and Viticulture and Enology departments over the last three years, as well as Grad Studies. Should I list them all by name? There is probably ~12 of them
